### ISSUE TITLE
Scouts feedback

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/scouts-video#1]
@PhilipHarney There's some text changes suggester in your feedback which make it difficult to turn into an issue. Can you check the comments on this doc and fix here?

https://docs.google.com/document/d/1_NImPSaqJCCX5_MTvyUE-DO05tAIvdnGyJ7kQ0AmuFw/edit#heading=h.2t91d0sii3k5

**Comment by PhilipHarney** [comment]
Fixed all the issues bar the safeguarding ones. I assume I wait on them to come back with the feedback from their team?
